/* =========================================================
   MIS ART FEST 2026
   SUPABASE DATABASE
   ========================================================= */

/* ---------------------------------------------------------
   1. HOUSES
   --------------------------------------------------------- */

create table if not exists public.houses (
    id bigint generated by default as identity primary key,
    name text not null unique,
    color text not null,
    created_at timestamptz default now()
);


/* ---------------------------------------------------------
   2. EVENTS
   --------------------------------------------------------- */

create table if not exists public.events (
    id bigint generated by default as identity primary key,
    name text not null,
    section text,
    category text,
    event_type text default 'individual',
    created_at timestamptz default now()
);


/* ---------------------------------------------------------
   3. RESULTS
   --------------------------------------------------------- */

create table if not exists public.results (
    id bigint generated by default as identity primary key,

    event_id bigint references public.events(id)
        on delete cascade,

    student_name text,
    class_name text,

    house_id bigint references public.houses(id)
        on delete cascade,

    position integer,
    points integer not null default 0,

    created_at timestamptz default now(),
    updated_at timestamptz default now()
);


/* ---------------------------------------------------------
   4. DEFAULT HOUSES
   --------------------------------------------------------- */

insert into public.houses (name, color)
values
    ('Crimson', '#C62828'),
    ('Verdant', '#2E7D32'),
    ('Azure', '#1565C0'),
    ('Golden', '#F9A825')
on conflict (name) do nothing;


/* ---------------------------------------------------------
   5. ROW LEVEL SECURITY
   --------------------------------------------------------- */

alter table public.houses enable row level security;
alter table public.events enable row level security;
alter table public.results enable row level security;


/* ---------------------------------------------------------
   6. PUBLIC READ ACCESS
   --------------------------------------------------------- */

drop policy if exists "Public can view houses"
on public.houses;

create policy "Public can view houses"
on public.houses
for select
to anon, authenticated
using (true);


drop policy if exists "Public can view events"
on public.events;

create policy "Public can view events"
on public.events
for select
to anon, authenticated
using (true);


drop policy if exists "Public can view results"
on public.results;

create policy "Public can view results"
on public.results
for select
to anon, authenticated
using (true);


/* ---------------------------------------------------------
   7. AUTHENTICATED TEACHER ACCESS
   --------------------------------------------------------- */

drop policy if exists "Teachers can insert events"
on public.events;

create policy "Teachers can insert events"
on public.events
for insert
to authenticated
with check (true);


drop policy if exists "Teachers can update events"
on public.events;

create policy "Teachers can update events"
on public.events
for update
to authenticated
using (true)
with check (true);


drop policy if exists "Teachers can delete events"
on public.events;

create policy "Teachers can delete events"
on public.events
for delete
to authenticated
using (true);


drop policy if exists "Teachers can insert results"
on public.results;

create policy "Teachers can insert results"
on public.results
for insert
to authenticated
with check (true);


drop policy if exists "Teachers can update results"
on public.results;

create policy "Teachers can update results"
on public.results
for update
to authenticated
using (true)
with check (true);


drop policy if exists "Teachers can delete results"
on public.results;

create policy "Teachers can delete results"
on public.results
for delete
to authenticated
using (true);


/* ---------------------------------------------------------
   8. REALTIME
   --------------------------------------------------------- */

alter publication supabase_realtime
add table public.houses;

alter publication supabase_realtime
add table public.events;

alter publication supabase_realtime
add table public.results;
